config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  get '/map', to:'events#map'
  get '/profile', to:'events#profile'
  resource :calendar, only: [:show], controller: :calendar
  resources :map
  resources :events do
    resources :categories
    resources :attend
    resources :maybe_attend
  end
end

app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :user
  belongs_to :event, counter_cache: true

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :category
  has_many :attends
  has_many :users, through: :attends
  has_many :maybe_attends
  has_many :photo


  geocoded_by :full_street_address

  validates :title, presence: true
  validates :details, presence: true
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  after_validation :geocode, if: :address_changed?

  def owner_or_admin?(logged_in_user)
    user == logged_in_user || logged_in_user.admin
  end

  def full_street_address
    "#{address}#{city}#{state}"
  end

  def attend_terminator(user)
    if attends.find_by(user_id: user)
      attends.find_by(user_id: user).destroy
    elsif maybe_attends.find_by(user_id: user)
      maybe_attends.find_by(user_id: user).destroy
    end
  end
end

app/models/maybe_attend.rb
class MaybeAttend < ActiveRecord::Base
  belongs_to :user
  belongs_to :event, counter_cache: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :attends
  has_many :maybe_attends
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attend_controller.rb
class AttendController < ApplicationController
  before_action :authenticate_user!
  def create
    @attend = Attend.new
    @event = Event.find(params[:event_id])
    @attend.event = @event
    @attend.user = current_user

    @event.attend_terminator(current_user)
    @attend.save

    redirect_to event_path(@attend.event)
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = Event.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :map]
  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.page(params[:page]).order(attends_count: :desc)
    respond_to do |format|
      format.json {render json: @events}
      format.html {@events}
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      flash[:notice] = "Event Saved"
      redirect_to event_path(@event)
    else
      flash[:notice] = "Invalid Input"
      render :new
    end
  end

  def edit
    access_to_event?(current_user)
  end

  def update
    access_to_event?(current_user)
    if @event.update(event_params)
      flash[:notice] = "Event Information Updated"
      redirect_to event_path
    else
      flash[:notice] = "Invalid Event Submission"
      render :edit
    end
  end

  def profile
    @attends = Attend.all.where(user_id: current_user)
    @maybe_attends = MaybeAttend.all.where(user_id: current_user)
    @events = Event.all.where(user_id: current_user)
  end

  def destroy
    access_to_event?(current_user)
    if @event.destroy
      flash[:notice] = "Event Successfully Deleted"
      redirect_to calendar_path
    else
      flash[:notice] = "Event was not deleted"
    end
  end

  def access_to_event?(current_user)
    if current_user.admin
      @event = Event.find(params[:id])
    else
      @event = current_user.events.find(params[:id])
    end
  end

  protected
  def event_params
    params.require(:event).permit(:title, :start_time, :end_time, :date,
      :details, :category_id, :address, :address_2, :city, :state, :zip_code,
      :longitude, :latitude, :photo)
  end
end

app/controllers/maybe_attend_controller.rb
class MaybeAttendController < ApplicationController
  before_action :authenticate_user!
  def create
    @maybe_attend = MaybeAttend.new
    @event = Event.find(params[:event_id])
    @maybe_attend.event = @event
    @maybe_attend.user = current_user

    @event.attend_terminator(current_user)
    @maybe_attend.save

    redirect_to event_path(@maybe_attend.event)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/calendar/show.html.haml
.column
  .medium-12.columns.text-center
    .row
      .small-12.comlumns.text-center.small-offset-3.column
        .small-1.columns
          Last Month
          / = link_to calendar_path(date: @date - 1.month), class: "button tiny right"
        .small-4.columns
          %h2.white-text
            = "#{@date.strftime("%B")} #{@date.year}"
        .small-1.columns
          Next Month
          / = link_to calendar_path(date: @date + 1.month), class: "button tiny left"
        .small-offset-3.column
    .medium-12.columns.medium-offset-1.column
      .medium-8.columns
        = calendar @date do |date|
          = date.day
          %div.scrollable
            %ul
            -@events_by_date.each do |event|
              -if event.date == date
                %li= link_to event.title, event
      .medium-2.columns

app/views/events/_form.html.haml
- if @event.errors.any?
  #error_explanation
    %h2
      = pluralize(@event.errors.count, "error")
      prohibited this event from being saved:
    %ul
      - @event.errors.full_messages.each do |message|
        %li= message
.panel#dark-panel
  = form_for @event do |f|
    .row
      .large-7.columns
        .small-6.columns
          .new_event
            = f.text_field :title, placeholder: "Title"
            .form
    .row
      .large-7.columns
        .small-4.columns
          .new_event.white-text
            = f.label :start_time
            = f.time_field :start_time
        .small-4.columns
          .new_event.white-text
            = f.label :end_time
            = f.time_field :end_time
        .small-4.columns
          .new_event.white-text
            = f.label :date
            = f.date_field :date, default: Date.today
    .row
      .large-7.columns
        .large-4.columns
          .new_event.white-text
            = f.label :category_id
            = f.select :category_id, Category.all.collect { |a| [a.category, a.id] }
    .row
      .large-7.columns
        .small-6.columns
          .new_event
          = f.text_field :address, placeholder: "Address"
        .small-6.columns
          .new_event
          = f.text_field :address_2, placeholder: "Address 2"
    .row
      .large-7.columns
        .small-4.columns
          .new_event
            = f.text_field :city, placeholder: "City"
        .small-4.columns
          .new_event
            = f.select :state, options_for_select(us_states)
        .small-4.columns
          .new_event
            = f.text_field :zip_code, placeholder: "Zip Code"
    .row
      .large-7.columns
        .large-12.columns
          = f.text_area :details, placeholder: "Details"
          %div
            = f.label :photo, 'Event photo'
            = f.file_field :photo
    .row
      .large-7.columns
        .large-3.columns
          .post
            = f.submit "Add event", class: "radius button tiny"

app/views/events/edit.html.haml
.row
  .columns.center-text
    %h1.white-text
      Edit Event
    = render 'form'

app/views/events/index.html.haml
.row
  .large-12.columns
    %ul
      - @events.each do |event|
        .large-4.columns.left
          .panel.white-text.index-panel#dark-panel
            .row
              #photo_or_map
                -if event.photo_url.to_s != ""
                  = image_tag event.photo_url.to_s
                -else
                  = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{event.latitude}%2C#{event.longitude}"
            .row
              %h3
                .white-text
                  = link_to event.title, event
              = event.category.category
              .event_date
                #{event.date}
              .event_time
                = event.start_time.strftime("%I:%M%p") + " - " + event.end_time.strftime("%I:%M%p")

app/views/events/map.html.haml
#map

%script{src: "http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"}
%script{src: "https://api.tiles.mapbox.com/mapbox.js/v2.1.8/mapbox.js"}

app/views/events/new.html.haml
.row
  .columns.center-text
    %h1.white-text
      New Event
    = render 'form'

app/views/events/profile.html.haml
.row
  .large-12.columns
    %h1.white-text.text-center#dark-panel
      Attending
      %ul
        - @attends.each do |attend|
          .large-4.columns.left
            .panel.white-text.index-panel#dark-panel
              .row
                #photo_or_map
                  -if attend.event.photo_url.to_s != ""
                    = image_tag attend.event.photo_url.to_s
                  -else
                    = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{attend.event.latitude}%2C#{attend.event.longitude}"
              .row
                %h3
                  .white-text
                    = link_to attend.event.title, attend.event
                = attend.event.category.category
                .attend.event_date
                  #{attend.event.date}
                .attend.event_time
                  = attend.event.start_time.strftime("%I:%M%p") + " - " + attend.event.end_time.strftime("%I:%M%p")
.row
  %h1.white-text.text-center#dark-panel
    Maybe Attending
    %ul
      - @maybe_attends.each do |maybe_attend|
        .large-4.columns.left
          .panel.white-text.index-panel#dark-panel
            .row
              #photo_or_map
                -if maybe_attend.event.photo_url.to_s != ""
                  = image_tag maybe_attend.event.photo_url.to_s
                -else
                  = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{maybe_attend.event.latitude}%2C#{maybe_attend.event.longitude}"
            .row
              %h3
                .white-text
                  = link_to maybe_attend.event.title, maybe_attend.event
              = maybe_attend.event.category.category
              .maybe_attend.event_date
                #{maybe_attend.event.date}
              .maybe_attend.event_time
                = maybe_attend.event.start_time.strftime("%I:%M%p") + " - " + maybe_attend.event.end_time.strftime("%I:%M%p")
.row
  %h1.white-text.text-center#dark-panel
    Added Events
    %ul
      - @events.each do |event|
        .large-4.columns.left
          .panel.white-text.index-panel#dark-panel
            .row
              #photo_or_map
                -if event.photo_url.to_s != ""
                  = image_tag event.photo_url.to_s
                -else
                  = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{event.latitude}%2C#{event.longitude}"
            .row
              %h3
                .white-text
                  = link_to event.title, event
              = event.category.category
              .event.event_date
                #{event.date}
              .event.event_time
                = event.start_time.strftime("%I:%M%p") + " - " + event.end_time.strftime("%I:%M%p")

app/views/events/show.html.haml
.row
  .columns
    .panel.white-text#dark-panel
      .row
        .large-4.columns#image
          = image_tag @event.photo_url.to_s
        .large-8.columns
          .row
            .medium-8.columns
              %h3.event#event_new_title
                .white-text.event_editable#event_title
                  = @event.title
              = @event.category.category
            .medium-4.columns
              #mini_map
                = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}"
          .row
            .medium-8.columns
              %span
                .event_date
                  #{@event.date}
                .event_time
                  = @event.start_time.strftime("%I:%M%p") + " - " + @event.end_time.strftime("%I:%M%p")
            .medium-4.columns.white-text
              .event_where.text-right
                %div
                  #{@event.address}
                %div
                  = @event.address_2
                %div
                  = @event.city
                  , #{@event.state}
                %div
                  = @event.zip_code
          .row
            .large-10.columns
              Details:
              %div.event_editable#event_details
                #{@event.details}
      .row
        .columns
          .rows
            .large-4.columns
              %div
                - if @event.attends_count == 1
                  = "#{@event.attends_count} person is attending this event"
                - else
                  = "#{@event.attends_count} people are attending this event"
              %div
                - if @event.maybe_attends_count == 1
                  = "#{@event.maybe_attends_count} person maybe attending this event"
                - else
                  = "#{@event.maybe_attends_count} people might be going to this event"
              - if current_user
                .button.tiny.radius
                  = link_to "Attending", event_attend_index_path(@event), method: :post
                .button.tiny.radius
                  = link_to "Maybe", event_maybe_attend_index_path(@event), method: :post
                .row
                  .column
                    - if @event.owner_or_admin?(current_user)
                      %div.button.tiny.radius
                        = link_to "Edit event", edit_event_path(@event), class: "edit_event"
                      %div.button.tiny.radius
                        = link_to "Delete event", event_path(@event), method: :delete

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title= "Wassup?"
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %meta{content: "initial-scale=1,maximum-scale=1,user-scalable=no", name: "viewport"}/
    %link{:href => "images/icons/1-favicon.ico", :rel => "shortcut icon", :type => "image/ico"}
    %link{href: "https://api.tiles.mapbox.com/mapbox.js/v2.1.8/mapbox.css", rel: "stylesheet"}
    %link{href: "http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css", rel: "stylesheet"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %nav.top-bar
    %ul.title-area
      %li.name
        %h1
          %a{href: "/", id: "sup"} Wassup?
    %section.top-bar-section#this
      %ul
        %li= link_to 'featured', events_path, class: "radius button large "
        %li= link_to 'calendar', calendar_path, class: "radius button tiny "
        %li= link_to 'map', '/map',class: "radius button tiny "
    %section.top-bar-section
      %ul.right
        - if current_user
          %li= link_to 'My Events', '/profile', class: "radius button tiny nav-buttons"
          %li= link_to 'Add Event', new_event_path, class: "radius button tiny"
          %li= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "radius button tiny "
        - else
          %li= link_to 'Sign Up', new_user_registration_path, class: "radius button tiny "
          %li= link_to 'Sign In', new_user_session_path, class: "radius button tiny "
  %p.notice= notice
  %p.alert= alert
  %body
    = yield

    %script{src: "/assets/javascripts/form_event.js"}
    = javascript_include_tag "application"